/**
 * Phrases that must never appear in any AI output or user-facing result.
 * The backend rejects/sanitizes responses containing them; frontend tests
 * assert they never render. Single source of truth for both sides.
 */
export const FORBIDDEN_RESULT_PHRASES = [
  'face recognition',
  'facial recognition',
  'identity match',
  'identity matching',
  'biometric',
  'exact lookalike',
  'exact-lookalike',
  'exact look-alike',
  'looks exactly like',
  'you look exactly',
  'same face',
  'identical face',
  'visual twin',
  'you are ',
  'the person is ',
  'recognized you',
  'we identified',
  'identified as',
  'تعرّف على الوجه',
  'التعرف على الوجه',
  'مطابقة الهوية',
  'مطابقة هوية',
  'بيومتري',
  'بيومترية',
  'شبيه مطابق',
  'يشبه تمامًا',
  'نفس الوجه',
  'أنت هو ',
  'أنت هي ',
  'الشخص هو ',
  'تم التعرف عليك',
  'تم التعرّف عليك',
  'حددنا هويتك',
] as const;

/**
 * Sensitive inference topics the game must never output about a person.
 */
export const FORBIDDEN_SENSITIVE_TOPICS = [
  'ethnicity',
  'religion',
  'health condition',
  'medical condition',
  'diagnosis',
  'attractiveness rating',
  'attractive',
  'beautiful',
  'handsome',
  'income',
  'wealthy',
  'nationality guess',
  'personality diagnosis',
  'sexual orientation',
  'sexuality',
  'religious belief',
  'years old',
  'age estimate',
  'الأصل العرقي',
  'العرق',
  'الدين',
  'المعتقد الديني',
  'الحالة الصحية',
  'تشخيص',
  'تقييم الجاذبية',
  'جذاب',
  'جميل',
  'وسيم',
  'الدخل',
  'جنسيتك',
  'تشخيص الشخصية',
  'شخصيته انطوائية',
  'الميول الجنسية',
] as const;
