/**
 * The advanced-global-traits-v2 trait taxonomy: 16 nested categories with 221
 * named visible, non-identifying trait fields. This is the schema contract
 * with Gemini (Prompt 1) AND the display contract for the frontend accordion —
 * field lists are consumed by the zod schema builder, the prompt template,
 * the test fixtures, and the i18n label keys, so the taxonomy is defined
 * exactly once here.
 *
 * Keys stay English camelCase in every language; VALUES are localized by the
 * model into the request's languageCode.
 */
export const TRAIT_CATEGORY_FIELDS = {
  imageQuality: [
    'lightingQuality',
    'sharpness',
    'faceVisibility',
    'faceAngle',
    'occlusionLevel',
    'visibleSide',
    'cameraDistance',
    'imageResolutionImpression',
    'shadowImpact',
    'confidenceLevel',
    'unclearAreas',
  ],
  overallFace: [
    'overallFaceShape',
    'overallFacialLength',
    'overallFacialWidth',
    'verticalProportion',
    'horizontalProportion',
    'facialSoftnessOrAngularAppearance',
    'visibleSymmetryImpression',
    'dominantVisibleFeatures',
    'generalVisibleVibeWords',
    'faceFullnessImpression',
  ],
  faceShapeAndProportions: [
    'upperFaceWidth',
    'midFaceWidth',
    'lowerFaceWidth',
    'faceLengthToWidthImpression',
    'templeWidth',
    'cheekWidth',
    'jawWidth',
    'chinWidth',
    'faceTapering',
    'facialBalance',
    'midfaceLength',
    'lowerFaceLength',
    'cheekToJawTransition',
    'cheekToTempleTransition',
    'facialPlaneImpression',
    'facialFeatureSpacing',
    'overallProportionNotes',
  ],
  foreheadAndHairline: [
    'foreheadHeight',
    'foreheadWidth',
    'foreheadShape',
    'foreheadSlopeImpression',
    'hairlineShape',
    'hairlineHeight',
    'hairlineDensity',
    'templeHairline',
    'widowPeakPresence',
    'foreheadVisibility',
    'foreheadToFaceRatio',
    'hairlineSymmetryImpression',
  ],
  hair: [
    'hairPresence',
    'hairColor',
    'hairColorTone',
    'hairColorUniformity',
    'hairTexture',
    'hairDensity',
    'hairVolume',
    'hairLength',
    'hairstyle',
    'hairDirection',
    'hairParting',
    'curlPattern',
    'wavePattern',
    'topHairShape',
    'sideHairShape',
    'hairShine',
    'hairNeatness',
    'hairContrastWithSkin',
    'hairMovementOrFlow',
    'hairGroomingLevel',
  ],
  eyebrows: [
    'eyebrowColor',
    'eyebrowThickness',
    'eyebrowDensity',
    'eyebrowLength',
    'eyebrowShape',
    'eyebrowArch',
    'eyebrowAngle',
    'eyebrowSpacing',
    'eyebrowPosition',
    'eyebrowSymmetryImpression',
    'eyebrowGrooming',
    'eyebrowTailShape',
    'eyebrowInnerShape',
    'eyebrowContrastWithSkin',
  ],
  eyes: [
    'visibleEyeColor',
    'eyeShape',
    'eyeSize',
    'eyeSpacing',
    'eyeDepthImpression',
    'eyelidType',
    'upperEyelidVisibility',
    'lowerEyelidVisibility',
    'eyeTilt',
    'outerCornerShape',
    'innerCornerShape',
    'underEyeArea',
    'eyelashVisibility',
    'eyeExpression',
    'eyeSymmetryImpression',
    'gazeDirection',
    'irisVisibility',
    'scleraVisibility',
    'browEyeDistance',
    'eyeOpenness',
  ],
  nose: [
    'noseLength',
    'noseWidth',
    'noseBridgeShape',
    'noseBridgeWidth',
    'noseBridgeHeightImpression',
    'noseTipShape',
    'noseTipDirection',
    'nostrilVisibility',
    'nostrilShape',
    'noseBaseWidth',
    'noseProfileIfVisible',
    'noseFaceProportion',
    'bridgeToTipTransition',
    'noseSymmetryImpression',
    'noseContourVisibility',
  ],
  cheeksAndCheekbones: [
    'cheekboneHeight',
    'cheekboneProminence',
    'cheekFullness',
    'cheekContour',
    'cheekHollowing',
    'midfaceVolume',
    'smileLinesVisibility',
    'cheekSymmetryImpression',
    'cheekShadowing',
    'cheekToNoseTransition',
    'cheekToJawTransition',
  ],
  mouthAndLips: [
    'mouthWidth',
    'lipFullness',
    'upperLipShape',
    'lowerLipShape',
    'upperToLowerLipRatio',
    'cupidBowVisibility',
    'lipColorImpression',
    'mouthCornerDirection',
    'smileVisibility',
    'smileIntensity',
    'teethVisibility',
    'mouthSymmetryImpression',
    'philtrumVisibility',
    'philtrumLengthImpression',
    'mouthExpression',
    'lipOutlineDefinition',
  ],
  jawlineAndChin: [
    'jawlineDefinition',
    'jawAngle',
    'jawWidth',
    'jawShape',
    'chinShape',
    'chinLength',
    'chinWidth',
    'chinProjectionImpression',
    'chinRoundnessOrSharpness',
    'lowerFaceStructure',
    'jawToNeckTransitionIfVisible',
    'mandibleVisibility',
    'jawSymmetryImpression',
    'chinToLipTransition',
    'chinContour',
  ],
  facialHair: [
    'beardPresence',
    'beardColor',
    'beardDensity',
    'beardLength',
    'beardCoverage',
    'beardStyle',
    'cheekBeardLine',
    'jawBeardLine',
    'neckBeardLineIfVisible',
    'chinBeardDensity',
    'mustachePresence',
    'mustacheColor',
    'mustacheDensity',
    'mustacheShape',
    'mustacheLength',
    'connectionBetweenMustacheAndBeard',
    'stubblePresence',
    'sideburnVisibility',
    'facialHairGroomingLevel',
    'facialHairContrastWithSkin',
  ],
  skinToneAndVisibleTexture: [
    'visibleSkinTone',
    'visibleUndertone',
    'rednessImpression',
    'tanImpression',
    'contrastWithHair',
    'visibleTextureOnly',
    'visibleFrecklesOrMarks',
    'visibleShineOrMatte',
    'visibleShadowAreas',
    'visibleColorEvenness',
    'visibleLightingEffectOnSkin',
    'noteNoHealthInference',
  ],
  expressionAndPose: [
    'facialExpression',
    'poseAngle',
    'headTilt',
    'cameraAngle',
    'smileIntensity',
    'expressionEnergy',
    'relaxedOrSeriousLook',
    'directnessToCamera',
    'shoulderVisibility',
    'neckVisibility',
    'postureImpressionIfVisible',
  ],
  groomingAndStyle: [
    'overallGrooming',
    'hairstyleVibe',
    'beardVibe',
    'polishedOrCasualLook',
    'publicScreenVibeWords',
    'fashionVisibilityIfAny',
    'accessoryVisibilityIfAny',
    'eyewearVisibility',
    'outfitColorIfVisible',
    'overallPresentationStyle',
  ],
  styleVibeDescriptors: [
    'softOrSharpVisibleVibe',
    'classicOrModernVisibleStyle',
    'casualOrFormalVisibleStyle',
    'cinematicVibeWords',
    'publicFigureMatchingHelpfulDescriptors',
    'strongestMatchingSignals',
    'weakestMatchingSignals',
  ],
} as const;

export type TraitCategoryKey = keyof typeof TRAIT_CATEGORY_FIELDS;

/** Category display/iteration order — object key order, frozen as a list. */
export const TRAIT_CATEGORY_KEYS = Object.keys(TRAIT_CATEGORY_FIELDS) as TraitCategoryKey[];

/** Field names of the structured uncertainty-notes block (each a bounded list). */
export const UNCERTAINTY_NOTE_FIELDS = [
  'imageLimitations',
  'unclearCategories',
  'lowConfidenceObservations',
  'traitsNotVisible',
] as const;

export type UncertaintyNoteField = (typeof UNCERTAINTY_NOTE_FIELDS)[number];

/** Total named trait fields across all categories (excluding uncertainty). */
export const TOTAL_TRAIT_FIELDS = Object.values(TRAIT_CATEGORY_FIELDS).reduce(
  (total, fields) => total + fields.length,
  0,
);

/** Upper bound accepted for the model-reported (and server-recomputed) traitCount. */
export const MAX_TRAIT_COUNT = TOTAL_TRAIT_FIELDS;

/** Longest accepted localized text for a single trait value. */
export const MAX_TRAIT_TEXT_LENGTH = 300;

/** compactTraitSummary carries the 20–35 strongest signals; hard cap 35. */
export const MAX_COMPACT_TRAIT_SUMMARY = 35;

/** Each uncertainty-notes list is capped at 10 entries (4 lists → ≤40 notes). */
export const MAX_UNCERTAINTY_NOTES_PER_FIELD = 10;
