import { z } from 'zod';

import { MAX_CANDIDATE_POOL, MIN_RESULT_COUNT } from '@twinzy/shared';

import {
  DEFAULT_AI_ENSEMBLE_MAX_CANDIDATES_PER_MODEL,
  DEFAULT_AI_ENSEMBLE_MAX_COMBINED_CANDIDATES,
  DEFAULT_AI_ENSEMBLE_MIN_SUCCESSFUL_PARTICIPANTS,
  DEFAULT_AI_ENSEMBLE_STEP_TIMEOUT_MS,
  DEFAULT_PUBLIC_FIGURE_CACHE_MAX_ITEMS,
  DEFAULT_PUBLIC_FIGURE_CACHE_TTL_SECONDS,
  DEFAULT_PUBLIC_FIGURE_MAX_RESPONSE_BYTES,
  DEFAULT_PUBLIC_FIGURE_REQUEST_TIMEOUT_MS,
  MAX_AI_ENSEMBLE_PARTICIPANTS,
  MAX_AI_RESPONSE_BYTES,
  MAX_GEMINI_TIMEOUT_MS,
  MAX_PUBLIC_FIGURE_CACHE_MAX_ITEMS,
  MAX_PUBLIC_FIGURE_CACHE_TTL_SECONDS,
  MIN_AI_ENSEMBLE_PARTICIPANTS,
  MIN_AI_RESPONSE_BYTES,
  MIN_GEMINI_TIMEOUT_MS,
  MIN_PUBLIC_FIGURE_CACHE_MAX_ITEMS,
  MIN_PUBLIC_FIGURE_CACHE_TTL_SECONDS,
} from './env-bounds.constants';

const disabledByDefault = z
  .enum(['true', 'false'])
  .default('false')
  .transform((value) => value === 'true');

export const advancedMatchingEnvShape = {
  AI_ADVANCED_MATCHING_ENABLED: disabledByDefault,
  AI_PUBLIC_FIGURE_CATALOG_ENABLED: disabledByDefault,
  AI_ENSEMBLE_ENABLED: disabledByDefault,
  AI_CROSS_CRITIQUE_ENABLED: disabledByDefault,
  AI_SECOND_RETRIEVAL_PASS_ENABLED: disabledByDefault,
  PUBLIC_FIGURE_ENRICHMENT_ENABLED: disabledByDefault,
  AI_ENSEMBLE_GENERATION_PARTICIPANTS: z.string().default(''),
  AI_ENSEMBLE_JUDGE_PARTICIPANTS: z.string().default(''),
  AI_ENSEMBLE_CRITIQUE_PARTICIPANTS: z.string().default(''),
  AI_ENSEMBLE_FINALIZER: z.string().default(''),
  AI_ENSEMBLE_MIN_SUCCESSFUL_PARTICIPANTS: z.coerce
    .number()
    .int()
    .min(MIN_AI_ENSEMBLE_PARTICIPANTS)
    .max(MAX_AI_ENSEMBLE_PARTICIPANTS)
    .default(DEFAULT_AI_ENSEMBLE_MIN_SUCCESSFUL_PARTICIPANTS),
  AI_ENSEMBLE_STEP_TIMEOUT_MS: z.coerce
    .number()
    .int()
    .min(MIN_GEMINI_TIMEOUT_MS)
    .max(MAX_GEMINI_TIMEOUT_MS)
    .default(DEFAULT_AI_ENSEMBLE_STEP_TIMEOUT_MS),
  AI_ENSEMBLE_MAX_CANDIDATES_PER_MODEL: z.coerce
    .number()
    .int()
    .min(MIN_RESULT_COUNT)
    .max(MAX_CANDIDATE_POOL)
    .default(DEFAULT_AI_ENSEMBLE_MAX_CANDIDATES_PER_MODEL),
  AI_ENSEMBLE_MAX_COMBINED_CANDIDATES: z.coerce
    .number()
    .int()
    .min(MIN_RESULT_COUNT)
    .max(MAX_CANDIDATE_POOL)
    .default(DEFAULT_AI_ENSEMBLE_MAX_COMBINED_CANDIDATES),
  PUBLIC_FIGURE_CACHE_TTL_SECONDS: z.coerce
    .number()
    .int()
    .min(MIN_PUBLIC_FIGURE_CACHE_TTL_SECONDS)
    .max(MAX_PUBLIC_FIGURE_CACHE_TTL_SECONDS)
    .default(DEFAULT_PUBLIC_FIGURE_CACHE_TTL_SECONDS),
  PUBLIC_FIGURE_CACHE_MAX_ITEMS: z.coerce
    .number()
    .int()
    .min(MIN_PUBLIC_FIGURE_CACHE_MAX_ITEMS)
    .max(MAX_PUBLIC_FIGURE_CACHE_MAX_ITEMS)
    .default(DEFAULT_PUBLIC_FIGURE_CACHE_MAX_ITEMS),
  PUBLIC_FIGURE_REQUEST_TIMEOUT_MS: z.coerce
    .number()
    .int()
    .min(MIN_GEMINI_TIMEOUT_MS)
    .max(MAX_GEMINI_TIMEOUT_MS)
    .default(DEFAULT_PUBLIC_FIGURE_REQUEST_TIMEOUT_MS),
  PUBLIC_FIGURE_MAX_RESPONSE_BYTES: z.coerce
    .number()
    .int()
    .min(MIN_AI_RESPONSE_BYTES)
    .max(MAX_AI_RESPONSE_BYTES)
    .default(DEFAULT_PUBLIC_FIGURE_MAX_RESPONSE_BYTES),
} as const;
