/**
 * Stable `data-testid` values for the whole game UI. Unit and e2e suites query
 * these instead of copy or DOM structure, so wording and markup can change
 * without breaking tests. One canonical source shared by every layer.
 */
export const TEST_IDS = {
  landingHero: 'landing-hero',
  playCta: 'play-cta',
  uploadCard: 'upload-card',
  uploadInput: 'upload-input',
  cameraCard: 'camera-card',
  cameraSwitch: 'camera-switch',
  cameraMirror: 'camera-mirror',
  consentCheckbox: 'consent-checkbox',
  analyzeButton: 'analyze-button',
  resultCountSelect: 'result-count-select',
  processing: 'processing',
  cancelProcessing: 'cancel-processing',
  resultList: 'result-list',
  resultExplanation: 'result-explanation',
  compactSummary: 'compact-summary',
  traitCount: 'trait-count',
  traitDetails: 'trait-details',
  traitCategory: 'trait-category',
  imageQuality: 'image-quality',
  translationBanner: 'translation-banner',
  translationLoader: 'translation-loader',
  translationRetry: 'translation-retry',
  shareModal: 'share-modal',
  shareLinkInput: 'share-link-input',
  copyLinkButton: 'copy-link-button',
  nativeShareButton: 'native-share-button',
  sharePlatformLink: 'share-platform-link',
  closeShareModal: 'close-share-modal',
  sharePage: 'share-page',
  shareCountdown: 'share-countdown',
  shareExpired: 'share-expired',
  shareNotFound: 'share-not-found',
  createOwnResult: 'create-own-result',
  resultCard: 'result-card',
  traitItem: 'trait-item',
  shareButton: 'share-button',
  retryButton: 'retry-button',
  retrySamePhoto: 'retry-same-photo',
  donateLink: 'donate-link',
  navDonateLink: 'nav-donate-link',
  paymentStep: 'payment-step',
  paypalButtons: 'paypal-buttons',
  paymobCardButton: 'paymob-card-button',
  paymentLoader: 'payment-loader',
  cancelPayment: 'cancel-payment',
  errorState: 'error-state',
  disclaimer: 'disclaimer',
  privacyNotice: 'privacy-notice',
  skipLink: 'skip-link',
  homeLink: 'home-link',
  localeSwitch: 'locale-switch',
  themeToggle: 'theme-toggle',
} as const;
